{ordered/set       ordered-collections.readers/ordered-set
 ordered/map       ordered-collections.readers/ordered-map
 interval/set      ordered-collections.readers/interval-set
 interval/map      ordered-collections.readers/interval-map
 range/map         ordered-collections.readers/range-map
 priority/queue    ordered-collections.readers/priority-queue
 multi/set         ordered-collections.readers/ordered-multiset
 vec/rope          ordered-collections.readers/rope
 string/rope       ordered-collections.readers/string-rope}
